// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package hcpvagrantregistry

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
	PackerBuildName       *string           `mapstructure:"packer_build_name" cty:"packer_build_name" hcl:"packer_build_name"`
	PackerBuilderType     *string           `mapstructure:"packer_builder_type" cty:"packer_builder_type" hcl:"packer_builder_type"`
	PackerCoreVersion     *string           `mapstructure:"packer_core_version" cty:"packer_core_version" hcl:"packer_core_version"`
	PackerDebug           *bool             `mapstructure:"packer_debug" cty:"packer_debug" hcl:"packer_debug"`
	PackerForce           *bool             `mapstructure:"packer_force" cty:"packer_force" hcl:"packer_force"`
	PackerOnError         *string           `mapstructure:"packer_on_error" cty:"packer_on_error" hcl:"packer_on_error"`
	PackerUserVars        map[string]string `mapstructure:"packer_user_variables" cty:"packer_user_variables" hcl:"packer_user_variables"`
	PackerSensitiveVars   []string          `mapstructure:"packer_sensitive_variables" cty:"packer_sensitive_variables" hcl:"packer_sensitive_variables"`
	Tag                   *string           `mapstructure:"box_tag" cty:"box_tag" hcl:"box_tag"`
	BoxDescription        *string           `mapstructure:"box_description" cty:"box_description" hcl:"box_description"`
	BoxPrivate            *bool             `mapstructure:"box_private" cty:"box_private" hcl:"box_private"`
	Version               *string           `mapstructure:"version" cty:"version" hcl:"version"`
	VersionDescription    *string           `mapstructure:"version_description" cty:"version_description" hcl:"version_description"`
	NoRelease             *bool             `mapstructure:"no_release" cty:"no_release" hcl:"no_release"`
	Architecture          *string           `mapstructure:"architecture" cty:"architecture" hcl:"architecture"`
	DefaultArchitecture   *string           `mapstructure:"default_architecture" cty:"default_architecture" hcl:"default_architecture"`
	ClientID              *string           `mapstructure:"client_id" cty:"client_id" hcl:"client_id"`
	ClientSecret          *string           `mapstructure:"client_secret" cty:"client_secret" hcl:"client_secret"`
	BoxDownloadUrl        *string           `mapstructure:"box_download_url" cty:"box_download_url" hcl:"box_download_url"`
	NoDirectUpload        *bool             `mapstructure:"no_direct_upload" cty:"no_direct_upload" hcl:"no_direct_upload"`
	BoxChecksum           *string           `mapstructure:"box_checksum" cty:"box_checksum" hcl:"box_checksum"`
	HcpApiAddress         *string           `mapstructure:"hcp_api_address" cty:"hcp_api_address" hcl:"hcp_api_address"`
	HcpAuthUrl            *string           `mapstructure:"hcp_auth_url" cty:"hcp_auth_url" hcl:"hcp_auth_url"`
	InsecureSkipTLSVerify *bool             `mapstructure:"insecure_skip_tls_verify" cty:"insecure_skip_tls_verify" hcl:"insecure_skip_tls_verify"`
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatConfig)
}

// HCL2Spec returns the hcl spec of a Config.
// This spec is used by HCL to read the fields of Config.
// The decoded values from this spec will then be applied to a FlatConfig.
func (*FlatConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"packer_build_name":          &hcldec.AttrSpec{Name: "packer_build_name", Type: cty.String, Required: false},
		"packer_builder_type":        &hcldec.AttrSpec{Name: "packer_builder_type", Type: cty.String, Required: false},
		"packer_core_version":        &hcldec.AttrSpec{Name: "packer_core_version", Type: cty.String, Required: false},
		"packer_debug":               &hcldec.AttrSpec{Name: "packer_debug", Type: cty.Bool, Required: false},
		"packer_force":               &hcldec.AttrSpec{Name: "packer_force", Type: cty.Bool, Required: false},
		"packer_on_error":            &hcldec.AttrSpec{Name: "packer_on_error", Type: cty.String, Required: false},
		"packer_user_variables":      &hcldec.AttrSpec{Name: "packer_user_variables", Type: cty.Map(cty.String), Required: false},
		"packer_sensitive_variables": &hcldec.AttrSpec{Name: "packer_sensitive_variables", Type: cty.List(cty.String), Required: false},
		"box_tag":                    &hcldec.AttrSpec{Name: "box_tag", Type: cty.String, Required: false},
		"box_description":            &hcldec.AttrSpec{Name: "box_description", Type: cty.String, Required: false},
		"box_private":                &hcldec.AttrSpec{Name: "box_private", Type: cty.Bool, Required: false},
		"version":                    &hcldec.AttrSpec{Name: "version", Type: cty.String, Required: false},
		"version_description":        &hcldec.AttrSpec{Name: "version_description", Type: cty.String, Required: false},
		"no_release":                 &hcldec.AttrSpec{Name: "no_release", Type: cty.Bool, Required: false},
		"architecture":               &hcldec.AttrSpec{Name: "architecture", Type: cty.String, Required: false},
		"default_architecture":       &hcldec.AttrSpec{Name: "default_architecture", Type: cty.String, Required: false},
		"client_id":                  &hcldec.AttrSpec{Name: "client_id", Type: cty.String, Required: false},
		"client_secret":              &hcldec.AttrSpec{Name: "client_secret", Type: cty.String, Required: false},
		"box_download_url":           &hcldec.AttrSpec{Name: "box_download_url", Type: cty.String, Required: false},
		"no_direct_upload":           &hcldec.AttrSpec{Name: "no_direct_upload", Type: cty.Bool, Required: false},
		"box_checksum":               &hcldec.AttrSpec{Name: "box_checksum", Type: cty.String, Required: false},
		"hcp_api_address":            &hcldec.AttrSpec{Name: "hcp_api_address", Type: cty.String, Required: false},
		"hcp_auth_url":               &hcldec.AttrSpec{Name: "hcp_auth_url", Type: cty.String, Required: false},
		"insecure_skip_tls_verify":   &hcldec.AttrSpec{Name: "insecure_skip_tls_verify", Type: cty.Bool, Required: false},
	}
	return s
}
